gdp:
  outputs:
    dev:
      dbname: "{{ env_var('PGDATABASE')}}"
      host: "{{ env_var('PGHOST')}}"
      pass: "{{ env_var('PGPASSWORD')}}"
      port: 5432
      schema: gdp
      threads: 4
      type: postgres
      user: "{{ env_var('PGUSER')}}"
  target: dev